AWS Migration Changes
Caleydo/ordino_product pull request #66
Opened 2021-12-16 15:04 UTC by keckelt

cherry-picked commit from develop

* Updates the URL of the Elastic Container Registry (ECR) repository, i.e., where the images get stored
* Updates the Cluster name from _caleydo_  to the new cluster _JKU_ASG_Cluster_

Note: For the build to succeed, the AWS Environment variables need to be updated on CircleCi.

2021-12-17 09:45 UTC, thinkh requested changes

2021-12-17 09:45 UTC, thinkh commented on .circleci/config.yml
> +              isTaskRunning=$(aws --output text ecs list-tasks --cluster JKU_ASG_Cluster --family ${awsFamily})
I think, the production cluster name is `ordino-public`. 

```suggestion
              isTaskRunning=$(aws --output text ecs list-tasks --cluster ordino-public --family ${awsFamily})
```

2021-12-17 09:45 UTC, thinkh commented on .circleci/config.yml
> +                aws --output text ecs stop-task --cluster JKU_ASG_Cluster --task ${taskId}
```suggestion
                aws --output text ecs stop-task --cluster ordino-public --task ${taskId}
```

2021-12-17 09:45 UTC, thinkh commented on .circleci/config.yml
> +              aws --output text ecs run-task --cluster JKU_ASG_Cluster --task-definition ${awsFamily} --started-by CircleCIAutoUpdate
```suggestion
              aws --output text ecs run-task --cluster ordino-public --task-definition ${awsFamily} --started-by CircleCIAutoUpdate
```

2021-12-28 12:36 UTC, keckelt commented
Thanks for the changes @thinkh! I've included your changes.

2022-08-16 11:14 UTC, thinkh commented
The changes are already integrated in the main branch.

2022-08-16 11:14 UTC, closed without merging